/*


*/
--3.
SELECT STUDENT_NAME
FROM TB_DEPARTMENT D,TB_STUDENT S
WHERE D.DEPARTMENT_NO=S.DEPARTMENT_NO
AND DEPARTMENT_NAME='국어국문학과'
AND SUBSTR(STUDENT_SSN,8,1)='2'
AND ABSENCE_YN='Y';

--4.
SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE STUDENT_NO IN ('A513079', 'A513090', 'A513091', 'A513110', 'A513119');
--5.
SELECT DEPARTMENT_NAME,CATEGORY
FROM TB_DEPARTMENT
WHERE CAPACITY BETWEEN '20' AND '30';
--6.
SELECT PROFESSOR_NAME
FROM TB_PROFESSOR
WHERE DEPARTMENT_NO IS NULL;
--7.
SELECT S.STUDENT_NAME,NVL(DEPARTMENT_NAME,'없음')
FROM TB_DEPARTMENT D,TB_STUDENT S
WHERE D.DEPARTMENT_NO=S.DEPARTMENT_NO;

SELECT B.CLASS_NO
FROM TB_CLASS T,TB_CLASS B
WHERE T.CLASS_NO=B.PREATTENDING_CLASS_NO;
--9.
SELECT DISTINCT CATEGORY
FROM TB_DEPARTMENT
ORDER BY 1;

--10.
SELECT STUDENT_NO,STUDENT_NAME,STUDENT_SSN
FROM TB_STUDENT
WHERE STUDENT_ADDRESS LIKE '%전주%'
AND ENTRANCE_DATE LIKE '02%'
AND ABSENCE_YN ='N';

--[Additional SELECT 함수]
SELECT STUDENT_NO,STUDENT_NAME,ENTRANCE_DATE
FROM TB_STUDENT
WHERE DEPARTMENT_NO='002'
ORDER BY 3;

--2.
SELECT PROFESSOR_NAME,PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE PROFESSOR_NAME NOT LIKE '___';

--3.
SELECT STUDENT_NAME 학생이름,SUBSTR(STUDENT_SSN,1,2)-EXTRACT(SUBSTR(YEAR FROM SYSDATE))-1 나이
FROM TB_STUDENT
WHERE SUBSTR(STUDENT_SSN,1,2) NOT IN '00';

--9.
SELECT S.STUDENT_NO,ROUND(AVG(POINT),1)
FROM TB_STUDENT S,TB_GRADE G
WHERE G.STUDENT_NO ='A517178'
AND STUDENT_NAME='한아름'
GROUP BY S.STUDENT_NO;

--10.
SELECT S.DEPARTMENT_NO 학과번호,COUNT(DISTINCT STUDENT_NAME) "학생수(명)"
FROM TB_DEPARTMENT D ,TB_STUDENT S
GROUP BY S.DEPARTMENT_NO
ORDER BY 1;

--11.
SELECT COUNT(*)
FROM TB_STUDENT
WHERE COACH_PROFESSOR_NO IS NULL;

SELECT SUBSTR(TERM_NO,1,4),ROUND(AVG(POINT),1)
FROM TB_GRADE G,TB_STUDENT S
WHERE SUBSTR(TERM_NO,1,4) BETWEEN '2001' AND '2004'
AND S.STUDENT_NAME ='김고운'AND S.STUDENT_NO='A112113'
GROUP BY SUBSTR(TERM_NO,1,4);