/*
            TEST용
*/

SELECT * FROM EMPLOYEE;

SELECT EMP_NAME,DEPT_CODE,CONCAT(SUBSTR(EMP_NO,1,2),'년')||CONCAT(SUBSTR(EMP_NO,3,2),'월')||CONCAT(SUBSTR(EMP_NO,5,2),'일') 합친거
        ,EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM TO_DATE(SUBSTR(EMP_NO,1,2),'RR')) "나이"
FROM EMPLOYEE;

--ANSI 구문
SELECT DEPT_ID,DEPT_TITLE,LOCATION_ID,LOCAL_NAME
FROM DEPARTMENT D
JOIN LOCATION L ON (D.LOCATION_ID=L.LOCAL_CODE);

--오라클 구문
SELECT DEPT_ID,DEPT_TITLE,SALARY
FROM EMPLOYEE E,DEPARTMENT D
WHERE DEPT_CODE(+)=DEPT_ID;
-->내가 기준으로 삼을 테이블며으이 컬럼명이 아니라 반대 테이블의 컬럼며에 (+)를 붙여준다.

-->ANSI 구문
SELECT EMP_NAME,SALARY,DEPT_TITLE
FROM EMPLOYEE
LEFT OUTER JOIN DEPARTMENT ON (DEPT_CODE=DEPT_ID);

SELECT EMP_NAME,SALARY,DEPT_TITLE
FROM EMPLOYEE E
RIGHT OUTER JOIN DEPARTMENT ON (DEPT_CODE=DEPT_ID);

SELECT EMP_NAME,SALARY,DEPT_TITLE
FROM EMPLOYEE E
FULL OUTER JOIN DEPARTMENT ON (DEPT_CODE=DEPT_ID);

--ANSI
SELECT EMP_NAME,SALARY,S.SAL_LEVEL
FROM EMPLOYEE E
JOIN SAL_GRADE S ON (SALARY BETWEEN MIN_SAL AND MAX_SAL);

SELECT E.EMP_ID 사번,E.EMP_NAME 사원명,E.MANAGER_ID 사수사번,M.EMP_NAME 사수명
FROM EMPLOYEE E, EMPLOYEE M
WHERE E.EMP_ID(+)=M.MANAGER_ID;

SELECT * FROM EMPLOYEE;
SELECT * FROM DEPARTMENT;
SELECT * FROM JOB;

-- 다 합쳐보자
SELECT E.EMP_ID 사번,E.EMP_NAME 사원명,E.MANAGER_ID 사수사번,M.EMP_NAME 사수명
FROM EMPLOYEE E,DEPARTMENT D, JOB J
WHERE E.DEPT_CODE=D.DEPT_ID
AND E.JOB_CODE=J.JOB_CODE;
